<div class="banner-desktop">
  <div class="banner-slider">
    <?php for ($i = 1; $i <= 3; $i++) : ?>
      <div class="banner-slider__inner">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId("raww-banner_slider-$i")->toHtml(); ?>
      </div>
    <?php endfor; ?>
  </div>
</div>

<div class="banner-mobile">
	<div class="banner-slider">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId("raww-banner_slider-mobile")->toHtml(); ?>
	</div>
</div>

<script>
     require([
      'jquery',
      'slick',
      'domReady!'
   ], function ($) {
      $(".banner-slider").slick({
        dots: false,
        infinite: true,
        autoplay: true,
        autoplaySpeed: 2500,
        arrows: false,
        fade: true,
        loop: true,
        slidesToShow: 1,
        slidesToScroll: 1,
        // responsive: [
        //             {
        //                 breakpoint: 1280,
        //                 settings: {
        //                     slidesToShow: 2,
        //                     slidesToScroll: 4
        //                 }
        //             },
        //             {
        //                 breakpoint: 1024,
        //                 settings: {
        //                     slidesToShow: 5,
        //                     slidesToScroll: 5
        //                 }
        //             },
        //             {
        //                 breakpoint: 768,
        //                 settings: {
        //                     slidesToShow: 4,
        //                     slidesToScroll: 4
        //                 }
        //             },
        //             {
        //                 breakpoint: 600,
        //                 settings: {
        //                     slidesToShow: 2,
        //                     slidesToScroll: 1
        //                 }
        //             }
        //         ]
      }
      );
   });

</script>