<div class="item product">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('raww-footer_nav-product')
        ->toHtml()
    ?>
</div>
<div class="item difference">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('raww-footer_nav-difference')
        ->toHtml()
    ?>
</div>
<div class="item service">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('raww-footer_nav-service')
        ->toHtml()
    ?>
</div>
<div class="item service extend">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('raww-footer_nav-service_extend')
        ->toHtml()
    ?>
</div>
<div class="item social">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('raww-footer_nav-social')
        ->toHtml()
    ?>
</div>
<div class="item about">
    <?php 
        echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('raww-footer_nav-about')
        ->toHtml()
    ?>
</div>